### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by marcofranssen** [jaredhanson/passport-openidconnect#24]
Looks like the project is on hold for a while. Can you please share if we can depend on this project or if we should switch to some different library.

Is there anyone who can elaborate on the production readiness of this library as it is still a version 0.0.1 on npm?

Looking forward to a reply.

**Comment by atomfried** [comment]
Also: I might contribute some fixes based on 0.0.1 from npm which however seems quite different from the git codebase. Will there be another release?
