### ISSUE TITLE
Doesn't return all data from user data endpoint

### ISSUE THREAD

**Issue by CallumBrankin** [jaredhanson/passport-openidconnect#43]
I'm currently using passport-openidconnect for PixelPin but the user data doesn't seem to return all the user when i ask for it using all the available scopes. It seems the JSON returned from the endpoint is restricted to email, email_verified, sub, nickname, given_name, family_name and birthdate(which returns incorrectly). I've used the PixelPin endpoint for Magento 2 and it returns all the data correctly so there has to be something wrong with passport-openidconnect.

**Comment by sanjitbauli** [comment]
@CallumBrankin can you explain how did you fix it?
