### ISSUE TITLE
Dynamic callback URL

### ISSUE THREAD

**Issue by atalis** [jaredhanson/passport-openidconnect#46]
Can the callback URL be set dynamically, in the authenticate() method, similarly to the option in FacebookStrategy (see some examples in https://github.com/jaredhanson/passport-facebook/issues/2):

app.get('/login', 
    passport.authenticate('facebook', {
        callbackURL:"/auth/callback",
        successRedirect : '...',
        failureRedirect : '/...'
    })
);

Using dynamic callback URLs is necessary for situations where authentication is done on a backend server with auth requests being proxied to it by a number of web servers, not a single one.  Or when multiple applications are hosted on a single Web server.

**Comment by atalis** [comment]
Apparently a similar option works for this package, even though it has not been documented.

**Comment by Degola** [comment]
what is this option?

**Comment by kinjalkparmar** [comment]
Can anyone please post the solution for this. Thanks.
